Update README.md
songquanpeng/message-pusher pull request #61
Opened 2023-04-26 18:33 UTC by o0oo0ooo0

Supplementary command.

2023-04-27 00:46 UTC, songquanpeng requested changes
改成以下内容吧：
```shell
# Install dependencies
npm install

# Run the app in the development mode
npm start

# Build the app for production
npm run build
```

2023-04-27 10:25 UTC, o0oo0ooo0 commented
好，我点那个re-review就可以了吧

2023-04-28 02:00 UTC, songquanpeng commented
貌似你推送错分支了，导致这里没有更新后的内容。

2023-04-30 13:06 UTC, o0oo0ooo0 commented
> > Add more commits by pushing to the [patch-1](https://github.com/o0oo0ooo0/message-pusher/tree/patch-1) branch on [o0oo0ooo0/message-pusher](https://github.com/o0oo0ooo0/message-pusher).
> 
> 貌似你推送错分支了，导致这里没有更新后的内容：

我重新开了个pr, 你看看行不行

2023-04-30 13:06 UTC, closed without merging